/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as dashboardRouteRouteImport } from './routes/(dashboard)/route'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ApiUploadthingIndexRouteImport } from './routes/api/uploadthing/index'
import { Route as dashboardFilesIndexRouteImport } from './routes/(dashboard)/files/index'
import { Route as authSignUpIndexRouteImport } from './routes/(auth)/sign-up/index'
import { Route as authSignInIndexRouteImport } from './routes/(auth)/sign-in/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as dashboardFilesUploadIndexRouteImport } from './routes/(dashboard)/files/upload/index'
import { Route as dashboardFilesFileIdIndexRouteImport } from './routes/(dashboard)/files/$fileId/index'

const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardRouteRoute = dashboardRouteRouteImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRouteImport,
} as any)
const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const ApiUploadthingIndexRoute = ApiUploadthingIndexRouteImport.update({
  id: '/api/uploadthing/',
  path: '/api/uploadthing/',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardFilesIndexRoute = dashboardFilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => dashboardRouteRoute,
} as any)
const authSignUpIndexRoute = authSignUpIndexRouteImport.update({
  id: '/sign-up/',
  path: '/sign-up/',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignInIndexRoute = authSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => authRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardFilesUploadIndexRoute =
  dashboardFilesUploadIndexRouteImport.update({
    id: '/files/upload/',
    path: '/files/upload/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)
const dashboardFilesFileIdIndexRoute =
  dashboardFilesFileIdIndexRouteImport.update({
    id: '/files/$fileId/',
    path: '/files/$fileId/',
    getParentRoute: () => dashboardRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in/': typeof authSignInIndexRoute
  '/sign-up/': typeof authSignUpIndexRoute
  '/files/': typeof dashboardFilesIndexRoute
  '/api/uploadthing/': typeof ApiUploadthingIndexRoute
  '/files/$fileId/': typeof dashboardFilesFileIdIndexRoute
  '/files/upload/': typeof dashboardFilesUploadIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/sign-in': typeof authSignInIndexRoute
  '/sign-up': typeof authSignUpIndexRoute
  '/files': typeof dashboardFilesIndexRoute
  '/api/uploadthing': typeof ApiUploadthingIndexRoute
  '/files/$fileId': typeof dashboardFilesFileIdIndexRoute
  '/files/upload': typeof dashboardFilesUploadIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(auth)': typeof authRouteRouteWithChildren
  '/(dashboard)': typeof dashboardRouteRouteWithChildren
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/(marketing)/': typeof marketingIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(auth)/sign-in/': typeof authSignInIndexRoute
  '/(auth)/sign-up/': typeof authSignUpIndexRoute
  '/(dashboard)/files/': typeof dashboardFilesIndexRoute
  '/api/uploadthing/': typeof ApiUploadthingIndexRoute
  '/(dashboard)/files/$fileId/': typeof dashboardFilesFileIdIndexRoute
  '/(dashboard)/files/upload/': typeof dashboardFilesUploadIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/auth/$'
    | '/sign-in/'
    | '/sign-up/'
    | '/files/'
    | '/api/uploadthing/'
    | '/files/$fileId/'
    | '/files/upload/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/auth/$'
    | '/sign-in'
    | '/sign-up'
    | '/files'
    | '/api/uploadthing'
    | '/files/$fileId'
    | '/files/upload'
  id:
    | '__root__'
    | '/(auth)'
    | '/(dashboard)'
    | '/(marketing)'
    | '/(marketing)/'
    | '/api/auth/$'
    | '/(auth)/sign-in/'
    | '/(auth)/sign-up/'
    | '/(dashboard)/files/'
    | '/api/uploadthing/'
    | '/(dashboard)/files/$fileId/'
    | '/(dashboard)/files/upload/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRouteRoute: typeof authRouteRouteWithChildren
  dashboardRouteRoute: typeof dashboardRouteRouteWithChildren
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiUploadthingIndexRoute: typeof ApiUploadthingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)': {
      id: '/(dashboard)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof dashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/api/uploadthing/': {
      id: '/api/uploadthing/'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing/'
      preLoaderRoute: typeof ApiUploadthingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/files/': {
      id: '/(dashboard)/files/'
      path: '/files'
      fullPath: '/files/'
      preLoaderRoute: typeof dashboardFilesIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(auth)/sign-up/': {
      id: '/(auth)/sign-up/'
      path: '/sign-up'
      fullPath: '/sign-up/'
      preLoaderRoute: typeof authSignUpIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/sign-in/': {
      id: '/(auth)/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof authSignInIndexRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/files/upload/': {
      id: '/(dashboard)/files/upload/'
      path: '/files/upload'
      fullPath: '/files/upload/'
      preLoaderRoute: typeof dashboardFilesUploadIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
    '/(dashboard)/files/$fileId/': {
      id: '/(dashboard)/files/$fileId/'
      path: '/files/$fileId'
      fullPath: '/files/$fileId/'
      preLoaderRoute: typeof dashboardFilesFileIdIndexRouteImport
      parentRoute: typeof dashboardRouteRoute
    }
  }
}

interface authRouteRouteChildren {
  authSignInIndexRoute: typeof authSignInIndexRoute
  authSignUpIndexRoute: typeof authSignUpIndexRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authSignInIndexRoute: authSignInIndexRoute,
  authSignUpIndexRoute: authSignUpIndexRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

interface dashboardRouteRouteChildren {
  dashboardFilesIndexRoute: typeof dashboardFilesIndexRoute
  dashboardFilesFileIdIndexRoute: typeof dashboardFilesFileIdIndexRoute
  dashboardFilesUploadIndexRoute: typeof dashboardFilesUploadIndexRoute
}

const dashboardRouteRouteChildren: dashboardRouteRouteChildren = {
  dashboardFilesIndexRoute: dashboardFilesIndexRoute,
  dashboardFilesFileIdIndexRoute: dashboardFilesFileIdIndexRoute,
  dashboardFilesUploadIndexRoute: dashboardFilesUploadIndexRoute,
}

const dashboardRouteRouteWithChildren = dashboardRouteRoute._addFileChildren(
  dashboardRouteRouteChildren,
)

interface marketingRouteRouteChildren {
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  authRouteRoute: authRouteRouteWithChildren,
  dashboardRouteRoute: dashboardRouteRouteWithChildren,
  marketingRouteRoute: marketingRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiUploadthingIndexRoute: ApiUploadthingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
